# Generated by Django 4.2.3 on 2023-08-06 14:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import portfoilo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField()),
                ('address', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to=portfoilo.models.path_and_rename)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoilo.category')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to=portfoilo.models.path_and_rename)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=255)),
                ('freelance', models.BooleanField(default=False)),
                ('degree', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_type', models.CharField(choices=[('EDU', 'Education'), ('EXP', 'Professional Experience')], max_length=3)),
                ('name', models.CharField(max_length=255)),
                ('years', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('description_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=portfoilo.models.path_and_rename)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portfoilo.portfolio')),
            ],
        ),
    ]
