# Generated by Django 4.2.3 on 2023-08-06 20:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfoilo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='description_details',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
